### PR TITLE
Add instructions for inline scripts for animate on scroll 

### PR DESCRIPTION
**Pull request by wing-puah**
As mention, the inline script that I'm using to animate when circle is scrolled into viewport. Thought it might be useful to others as well. This is a fast solution for me and I thought it was good enough to get things done. But if this is useful, I can also look into how I could implement into source code and make animate when in viewport as an option that they can trigger.

### CODE REVIEW

**Comment by thodorisbais** [comment]
Hey,

that's really cool!

Could we indeed include it as default functionality?
Thus, if the user wants to disable it, we should also provide an option for disabling it.

TB

**Comment by wing-puah** [comment]
Sure, I'll look into it again.

**Comment by thodorisbais** [comment]
@wing-puah any update on this?

**Comment by thodorisbais** [comment]
@wing-puah any updates here?

**Comment by chris--jones** [comment]
I think this PR is now redundant with #57 and #59

**Comment by thodorisbais** [comment]
Exactly the reason it was decided to keep that open. Unfortunately, that won't see the light of the day :/

**Pull request closed without merging**
