### PR TITLE
Allowed users to display text in circle even when the number is 0

### PR DESCRIPTION
**Pull request by whoisme555**

### CODE REVIEW

**Comment by thodorisbais** [comment]
Taking into account the ongoing discussion on #55 , I would like to merge this indeed, just to see whether it makes any change for you (, since for my, it looks fine on the one hand, and on the other hand, the introduced change doesn't seem to hurt that much).

However, I think this PR is missing the `displayTextAtZero` property in the configuration.
Could you please check it?

**Comment by whoisme555** [comment]
I noticed now that the previous conversation we had didn't include my images demonstrating it not working.

Regardless, the configuration should be done on the user's side upon init. 

For example: el.percircle({
displayTextAtZero: true
})

At which point it will pass to percircle's options and be accessible via my change. Of course, it will default to falsey so it won't affect existing users

**Comment by thodorisbais** [comment]
As discussed, I would like to try this solution, but given that we're talking about a new option/attribute, I think it's about time to add a table in the README mentioning all the supported options percircle comes with (, and of course, including the newly added option, `displayTextAtZero`).

Could that be part of this PR, @whoisme555 ?

**Comment by whoisme555** [comment]
Yeah, I'll try to add that in tomorrow

**Comment by thodorisbais** [comment]
Looking forward to it!

**Comment by thodorisbais** [comment]
Any luck? :-)

**Comment by thodorisbais** [comment]
Any update here, @whoisme555 ?

**Comment by thodorisbais** [comment]
Merging for now, given that we've heard nothing back from @whoisme555 . Will open a new issue for the README file to be updated accordingly.

**Pull request merged**
